// Leo's OpenCode bridge: registers the skills dir by path (OpenCode names
// each skill from its own frontmatter, so there is no leo: prefix here as
// there is on Claude Code and Hermes), injects the
// generated subagent roster from adapters/opencode/agents.json, assembles
// the using-leo policy plus the OpenCode mapping appendix and hands it to
// OpenCode through config.instructions (belt) and the
// experimental.chat.system.transform hook (braces), and guards Bash
// execution the same way the Claude Code harness does.
//
// Node builtins only, ESM. No external dependencies. No runtime frontmatter
// parsing and no env-var tier overrides: agents.json and this policy are
// both generated by scripts/render_adapters.py from config/models.json, the
// single source of truth every other harness also reads.
//
// Every read below is wrapped so a missing file degrades to "no
// skills/agents/policy" rather than breaking session start — same fail-open
// posture as hooks/session-start.py.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

const LEO_POLICY_MARKER = '<leo-policy>';

function localStateRoot() {
  return process.env.LEOS_AGENT_LOCAL_PATH || path.join(os.homedir(), '.leos-agent-local');
}

// A 6-line strip, not a YAML parser: the body starts after the second
// leading '---' fence line. Anything malformed just returns the raw text.
function stripFrontmatter(raw) {
  const lines = raw.split('\n');
  if (!lines.length || lines[0].trim() !== '---') return raw;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') {
      return lines.slice(i + 1).join('\n').replace(/^\n+/, '');
    }
  }
  return raw;
}

async function assemblePolicy() {
  let skillRaw;
  try {
    skillRaw = await readFile(path.join(ROOT, 'skills', 'using-leo', 'SKILL.md'), 'utf8');
  } catch {
    return null;
  }
  let body = stripFrontmatter(skillRaw).trimEnd();

  let mapping = '';
  try {
    mapping = (await readFile(
      path.join(ROOT, 'skills', 'using-leo', 'references', 'opencode-mapping.md'),
      'utf8',
    )).trimEnd();
  } catch {
    mapping = '';
  }

  let combined = mapping ? body + '\n\n' + mapping + '\n' : body + '\n';
  // Substitute AFTER the append: the mapping's own placeholders (e.g. a
  // claude-mapping-style workflow path) resolve too — same ordering
  // hooks/session-start.py:97 uses.
  combined = combined.split('${CLAUDE_PLUGIN_ROOT}').join(ROOT);

  return LEO_POLICY_MARKER + '\n' + combined + '</leo-policy>';
}

async function writePolicyFile(policy) {
  const dir = localStateRoot();
  const dest = path.join(dir, 'opencode-policy.md');
  try {
    await mkdir(dir, { recursive: true });
    await writeFile(dest, policy, 'utf8');
    return dest;
  } catch {
    return null;
  }
}

let policyCache;
async function getPolicy() {
  if (policyCache === undefined) {
    policyCache = await assemblePolicy();
  }
  return policyCache;
}

let policyPathCache;
async function getPolicyPath() {
  if (policyPathCache === undefined) {
    const policy = await getPolicy();
    policyPathCache = policy ? await writePolicyFile(policy) : null;
  }
  return policyPathCache;
}

async function loadAgents() {
  try {
    const raw = await readFile(path.join(ROOT, 'adapters', 'opencode', 'agents.json'), 'utf8');
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

let guardWarnedOnce = false;

export default async function leoPlugin(_ctx) {
  return {
    async config(config) {
      config.skills ||= {};
      config.skills.paths ||= [];
      const skillsDir = path.resolve(ROOT, 'skills');
      if (!config.skills.paths.includes(skillsDir)) {
        config.skills.paths.push(skillsDir);
      }

      const agents = await loadAgents();
      config.agent ||= {};
      Object.assign(config.agent, agents);

      const policyPath = await getPolicyPath();
      if (policyPath) {
        config.instructions ||= [];
        if (!config.instructions.includes(policyPath)) {
          config.instructions.push(policyPath);
        }
      }
    },

    // Fallback only, for the two upstream reports that either the config
    // hook or this array mutation is silently discarded (superpowers#1087,
    // opencode#17100): whichever channel actually works, exactly one copy
    // of the policy lands, because this checks for the marker first.
    'experimental.chat.system.transform': async (_input, output) => {
      const system = output && output.system;
      if (!Array.isArray(system)) return;
      if (system.some((s) => typeof s === 'string' && s.includes(LEO_POLICY_MARKER))) return;

      const policy = await getPolicy();
      if (policy) system.push(policy);
    },

    'tool.execute.before': async (input, output) => {
      if (!input || input.tool !== 'bash') return;
      const command = output && output.args && output.args.command;
      if (typeof command !== 'string' || !command) return;

      const cwd = (input && (input.directory || input.worktree || input.cwd)) || process.cwd();
      const payload = JSON.stringify({ tool_name: 'Bash', tool_input: { command }, cwd });
      const guardPath = path.join(ROOT, 'hooks', 'bash-guard.py');

      let exitCode;
      let stderr = '';
      try {
        exitCode = await new Promise((resolve, reject) => {
          const proc = spawn('python3', [guardPath], { stdio: ['pipe', 'ignore', 'pipe'] });
          proc.stderr.on('data', (d) => {
            stderr += d.toString();
          });
          proc.on('error', reject);
          proc.on('close', (code) => resolve(code));
          proc.stdin.write(payload);
          proc.stdin.end();
        });
      } catch (err) {
        if (!guardWarnedOnce) {
          guardWarnedOnce = true;
          console.error(
            '[leo guard] infra failure spawning bash-guard.py, allowing command:',
            err && err.message ? err.message : err,
          );
        }
        return; // infra fail-open
      }

      if (exitCode === 2) {
        throw new Error(stderr.trim() || '[leo guard] blocked');
      }
    },
  };
}
