// Leo's OpenCode bridge: registers the skills dir by path (OpenCode names
// each skill from its own frontmatter, so there is no leo: prefix here as
// there is on Claude Code and Hermes), injects the
// generated subagent roster from adapters/opencode/agents.json, assembles
// the using-leo policy plus the OpenCode mapping appendix and hands it to
// OpenCode through config.instructions (belt) and the
// experimental.chat.system.transform hook (braces), and guards Bash
// execution the same way the Claude Code harness does.
//
// Node builtins only, ESM. No external dependencies. No runtime frontmatter
// parsing and no env-var tier overrides: agents.json and this policy are
// both generated by scripts/render_adapters.py from config/models.json, the
// single source of truth every other harness also reads.
//
// Every read below is wrapped so a missing file degrades to "no
// skills/agents/policy" rather than breaking session start — same fail-open
// posture as hooks/session-start.py.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

const LEO_POLICY_MARKER = '<leo-policy>';

function localStateRoot() {
  return process.env.LEOS_AGENT_LOCAL_PATH || path.join(os.homedir(), '.leos-agent-local');
}

// One OpenCode process serves several project directories at once (its own log
// shows one run= creating an instance per directory), and ESM caches this
// module once per process, so nothing below may key off process.cwd() or hold
// per-directory state in a bare module variable. The directory arrives on
// PluginInput and is threaded through every consumer instead.
function directoryKey(directory) {
  return createHash('sha256').update(directory).digest('hex').slice(0, 12);
}

// A 6-line strip, not a YAML parser: the body starts after the second
// leading '---' fence line. Anything malformed just returns the raw text.
function stripFrontmatter(raw) {
  const lines = raw.split('\n');
  if (!lines.length || lines[0].trim() !== '---') return raw;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') {
      return lines.slice(i + 1).join('\n').replace(/^\n+/, '');
    }
  }
  return raw;
}

async function assemblePolicy(directory) {
  let skillRaw;
  try {
    skillRaw = await readFile(path.join(ROOT, 'skills', 'using-leo', 'SKILL.md'), 'utf8');
  } catch {
    return null;
  }
  let body = stripFrontmatter(skillRaw).trimEnd();

  let mapping = '';
  try {
    mapping = (await readFile(
      path.join(ROOT, 'skills', 'using-leo', 'references', 'opencode-mapping.md'),
      'utf8',
    )).trimEnd();
  } catch {
    mapping = '';
  }

  let combined = mapping ? body + '\n\n' + mapping + '\n' : body + '\n';
  // Substitute AFTER the append: the mapping's own placeholders (e.g. a
  // claude-mapping-style workflow path) resolve too — same ordering
  // hooks/session-start.py:97 uses.
  combined = combined.split('${CLAUDE_PLUGIN_ROOT}').join(ROOT);

  let policy = LEO_POLICY_MARKER + '\n' + combined + '</leo-policy>';

  // Memory rides in its own envelope after the policy. Spawned rather than
  // reimplemented in JS: memory.py already owns the store, the projection and
  // the marker engine, and a fourth copy of that renderer would drift.
  const memory = await memoryBlock(directory);
  if (memory) {
    policy += '\n\n<leo-memory>\n' + memory + '\n</leo-memory>';
  }
  return policy;
}

// Hard-kills after 4s: OpenCode session start must not hang on a memory store
// living on a slow or unreachable filesystem. Any failure yields '' and the
// session proceeds with policy only.
//
// `memory.py session` renders the block for the repo it is run in, so the
// directory has to be the session's, not the server's: process.cwd() here
// would serve one project's repo-scoped memories to every other project the
// same OpenCode process is hosting.
function memoryBlock(directory) {
  return new Promise((resolve) => {
    let done = false;
    const finish = (value) => { if (!done) { done = true; resolve(value); } };
    try {
      const child = spawn('python3', [path.join(ROOT, 'scripts', 'memory.py'), 'session'], {
        cwd: directory,
        stdio: ['ignore', 'pipe', 'ignore'],
      });
      const timer = setTimeout(() => { try { child.kill('SIGKILL'); } catch {} finish(''); }, 4000);
      let out = '';
      child.stdout.on('data', (chunk) => { out += chunk.toString(); });
      child.on('error', () => { clearTimeout(timer); finish(''); });
      child.on('close', (code) => {
        clearTimeout(timer);
        finish(code === 0 ? out.trim() : '');
      });
    } catch {
      finish('');
    }
  });
}

// Named per directory: the memory envelope inside is repo-scoped, so a single
// shared filename would have each project's instance overwriting the file the
// other projects' config.instructions already point at.
async function writePolicyFile(policy, directory) {
  const dir = localStateRoot();
  const dest = path.join(dir, `opencode-policy-${directoryKey(directory)}.md`);
  try {
    await mkdir(dir, { recursive: true });
    await writeFile(dest, policy, 'utf8');
    return dest;
  } catch {
    return null;
  }
}

// Keyed by directory for the same reason. A bare module variable is shared by
// every instance in the process, which would pin whichever project started
// first and serve its memories to the rest.
const policyCache = new Map();
async function getPolicy(directory) {
  if (!policyCache.has(directory)) {
    policyCache.set(directory, await assemblePolicy(directory));
  }
  return policyCache.get(directory);
}

const policyPathCache = new Map();
async function getPolicyPath(directory) {
  if (!policyPathCache.has(directory)) {
    const policy = await getPolicy(directory);
    policyPathCache.set(directory, policy ? await writePolicyFile(policy, directory) : null);
  }
  return policyPathCache.get(directory);
}

async function loadAgents() {
  try {
    const raw = await readFile(path.join(ROOT, 'adapters', 'opencode', 'agents.json'), 'utf8');
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

let guardWarnedOnce = false;

export default async function leoPlugin(ctx) {
  // The only place the session's directory is available. tool.execute.before
  // receives just {tool, sessionID, callID} (@opencode-ai/plugin's own types),
  // so reading a directory off that input yields undefined every time and
  // falls through to the server's cwd — a different tree whenever one process
  // hosts more than one project.
  const directory = (ctx && (ctx.directory || ctx.worktree)) || process.cwd();

  return {
    async config(config) {
      config.skills ||= {};
      config.skills.paths ||= [];
      const skillsDir = path.resolve(ROOT, 'skills');
      if (!config.skills.paths.includes(skillsDir)) {
        config.skills.paths.push(skillsDir);
      }

      const agents = await loadAgents();
      config.agent ||= {};
      Object.assign(config.agent, agents);

      const policyPath = await getPolicyPath(directory);
      if (policyPath) {
        config.instructions ||= [];
        if (!config.instructions.includes(policyPath)) {
          config.instructions.push(policyPath);
        }
      }
    },

    // Fallback only, for the two upstream reports that either the config
    // hook or this array mutation is silently discarded (superpowers#1087,
    // opencode#17100): whichever channel actually works, exactly one copy
    // of the policy lands, because this checks for the marker first.
    'experimental.chat.system.transform': async (_input, output) => {
      const system = output && output.system;
      if (!Array.isArray(system)) return;
      if (system.some((s) => typeof s === 'string' && s.includes(LEO_POLICY_MARKER))) return;

      const policy = await getPolicy(directory);
      if (policy) system.push(policy);
    },

    'tool.execute.before': async (input, output) => {
      if (!input || input.tool !== 'bash') return;
      const command = output && output.args && output.args.command;
      if (typeof command !== 'string' || !command) return;

      // bash-guard expands relative targets against this cwd, so the wrong
      // one misjudges in both directions: a home-level delete read as safe,
      // a project-local delete read as critical.
      const payload = JSON.stringify({
        tool_name: 'Bash',
        tool_input: { command },
        cwd: directory,
      });
      const guardPath = path.join(ROOT, 'hooks', 'bash-guard.py');

      let exitCode;
      let stderr = '';
      try {
        exitCode = await new Promise((resolve, reject) => {
          const proc = spawn('python3', [guardPath], { stdio: ['pipe', 'ignore', 'pipe'] });
          proc.stderr.on('data', (d) => {
            stderr += d.toString();
          });
          proc.on('error', reject);
          proc.on('close', (code) => resolve(code));
          proc.stdin.write(payload);
          proc.stdin.end();
        });
      } catch (err) {
        if (!guardWarnedOnce) {
          guardWarnedOnce = true;
          console.error(
            '[leo guard] infra failure spawning bash-guard.py, allowing command:',
            err && err.message ? err.message : err,
          );
        }
        return; // infra fail-open
      }

      if (exitCode === 2) {
        throw new Error(stderr.trim() || '[leo guard] blocked');
      }
    },
  };
}
