"""README is the setup surface for every supported harness."""

import os
import unittest


REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class TestReadmeInstall(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(os.path.join(REPO, "README.md"), encoding="utf-8") as fh:
            cls.readme = fh.read()
        with open(os.path.join(REPO, "plugins", "leo", "README.md"), encoding="utf-8") as fh:
            cls.payload_readme = fh.read()
        with open(os.path.join(REPO, "plugins", "leo", "skills", "setup", "SKILL.md"),
                  encoding="utf-8") as fh:
            cls.setup_skill = fh.read()
        with open(os.path.join(REPO, "CONTRIBUTING.md"), encoding="utf-8") as fh:
            cls.contributing = fh.read()
        with open(os.path.join(REPO, "SECURITY.md"), encoding="utf-8") as fh:
            cls.security = fh.read()

    def test_native_install_commands(self):
        for command in (
            "claude plugin marketplace add foxhatleo/leos-agent",
            "claude plugin install leo@leos-agent",
            "codex plugin marketplace add foxhatleo/leos-agent",
            "codex plugin add leo@leos-agent",
            "/add-plugin leo",
            "/add-plugin leo@https://github.com/foxhatleo/leos-agent",
            "hermes plugins install foxhatleo/leos-agent --enable",
            "opencode plugin leos-agent --global",
        ):
            with self.subTest(command=command):
                self.assertIn(command, self.readme)

    def test_no_hand_copied_npm_cache_path(self):
        """The old skills.paths fallback named a directory that does not
        exist: npm installs under ~/.cache/opencode/packages/<pkg>@<tag>/,
        and the literal drifted with an upstream layout change without
        anything noticing. plugin.js resolves its own location from
        import.meta.url, so no such path belongs in the docs at all.
        """
        self.assertNotIn("~/.cache/opencode/node_modules", self.readme)
        self.assertNotIn('"skills": { "paths"', self.readme)

    def test_opencode_config_filenames_are_both_named(self):
        for name in ("opencode.json", "opencode.jsonc"):
            with self.subTest(name=name):
                self.assertIn(name, self.readme)

    def test_models_and_retired_surfaces(self):
        for value in (
            "GPT-5.6 Sol",
            "Grok 4.5",
            "Composer 2.5",
            "gpt-5.6-terra",
            "moonshotai/kimi-k3",
            "z-ai/glm-5.2",
            "/model moonshotai/kimi-k3 --provider openrouter",
            "/model z-ai/glm-5.2 --provider openrouter",
        ):
            self.assertIn(value, self.readme)
        self.assertNotIn("./install.sh", self.readme)
        self.assertIn('"plugin": ["leos-agent"]', self.readme)
        self.assertIn("opencode.json", self.readme)
        self.assertIn("MCP", self.readme)
        self.assertIn("independently", self.readme)

    def test_public_install_and_recovery_contract(self):
        for text in (
            "codex plugin list --json",
            "/hooks",
            "leo:doctor",
            "first tool result",
            "leo:using-leo",
            "leo:setup enable hermes-memory",
            "$HERMES_HOME/SOUL.md",
            "Python 3.9",
            "macOS, Linux, and WSL",
            "Native Windows is unsupported",
            "GitHub Releases",
            "no hand-maintained changelog",
            "eight specialist roles",
            "Eight roles",
            "review-lens",
            "gpt-5.6-terra`, low",
            "opencode auth login",
            "opencode plugin leos-agent --global --force",
            "leo-<role>",
            "Slack workspace admin approval",
            "Google Cloud project",
            "local/",
        ):
            with self.subTest(text=text):
                self.assertIn(text, self.readme)
        self.assertNotIn("Version `7.0.0`", self.readme)
        self.assertNotIn("CHANGELOG", self.readme)
        self.assertNotIn("gpt-5.6-luna", self.readme)
        self.assertNotIn("seven specialist roles", self.readme)
        self.assertNotIn("six generated subagent roles", self.readme)

    def test_generated_opencode_readme_is_current_contract(self):
        self.assertIn("Generated by scripts/render_adapters.py", self.payload_readme)
        for text in (
            "OpenRouter",
            "leo-<name>",
            "leo-<role>",
            "adapters/opencode/agents.json",
            "leo-setup",
            "leo-using-leo",
            "opencode auth login",
            "opencode plugin leos-agent --global --force",
            "full purge",
            "7.0 recovery",
            "GitHub Releases",
        ):
            with self.subTest(text=text):
                self.assertIn(text, self.payload_readme)
        self.assertNotIn("`leo:using-leo`", self.payload_readme)
        self.assertIn("manual-only", self.payload_readme)

    def test_setup_documents_exact_removal_paths_and_backup_boundary(self):
        for text in (
            "claude mcp remove <name> --scope user",
            "codex mcp remove <name>",
            "hermes mcp remove <name>",
            "~/.cursor/mcp.json",
            "opencode.jsonc",
            "not a conflict-aware restore",
        ):
            with self.subTest(text=text):
                self.assertIn(text, self.setup_skill)

    def test_contributing_lists_the_release_acceptance_commands(self):
        for text in (
            "python3.14 -m unittest discover -s tests -v",
            "tools/release.py --check-version vX.Y.Z",
            "tools/release.py --build",
            "tools/release.py --stage-npm",
            "npm pack",
            "plugins/leo/config/MCP_PINS.md",
        ):
            with self.subTest(text=text):
                self.assertIn(text, self.contributing)
        self.assertIn("Replace `vX.Y.Z`", self.contributing)
        self.assertIn("release tag", self.contributing)

    def test_security_reporting_stays_private(self):
        self.assertIn("GitHub's private security advisory flow", self.security)
        self.assertIn("Do not open a public issue", self.security)
        self.assertNotIn("mailto:", self.security)


if __name__ == "__main__":
    unittest.main()
