"""The generated harness reference.

Five per-harness mapping files became one references/harnesses.md in 8.0, since
nothing detects the harness any more and shipping four files to be guessed
between was worse than shipping one to be read by section.

Everything here is derived from config/models.json rather than pinned as
literals. The old version hard-coded model names and note substrings, so a
retier failed a test that was only restating the config, and a note that went
stale in the config stayed green here.
"""

import json
import os
import re
import unittest


REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGIN = os.path.join(REPO, "plugins", "leo")
MODELS = os.path.join(PLUGIN, "config", "models.json")
REFERENCE = os.path.join(PLUGIN, "skills", "routing", "references", "harnesses.md")

SKILL_ROOTS = (os.path.join(PLUGIN, "skills"), os.path.join(PLUGIN, "skills-claude"))


def harness_title(config, harness):
    return config["harnesses"][harness]["title"]


def _skill_dirs():
    names = set()
    for root in SKILL_ROOTS:
        if not os.path.isdir(root):
            continue
        for name in os.listdir(root):
            if os.path.isfile(os.path.join(root, name, "SKILL.md")):
                names.add(name)
    return names


class TestHarnessReference(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(MODELS, encoding="utf-8") as fh:
            cls.config = json.load(fh)
        with open(REFERENCE, encoding="utf-8") as fh:
            cls.text = fh.read()
        cls.harnesses = sorted(cls.config["harnesses"])

    def test_reference_exists_and_is_generated(self):
        self.assertTrue(self.text.strip())
        self.assertIn("Generated by scripts/render_adapters.py", self.text)

    def test_it_says_how_to_tell_which_harness_this_is(self):
        """Without a detection hook, the reference has to carry the rule."""
        for token in (
            "LEOS_AGENT_HARNESS",
            "CURSOR_PLUGIN_ROOT",
            "PLUGIN_ROOT",
            "CLAUDE_PLUGIN_ROOT",
        ):
            with self.subTest(token=token):
                self.assertIn(token, self.text)

    def test_every_harness_has_a_section(self):
        for harness in self.harnesses:
            title = self.config["harnesses"][harness]["title"]
            with self.subTest(harness=harness):
                self.assertIn(f"## {title}", self.text)

    def test_every_tier_model_appears_in_its_section(self):
        for harness in self.harnesses:
            section = self._section(harness)
            for tier, row in self.config["harnesses"][harness]["tiers"].items():
                with self.subTest(harness=harness, tier=tier):
                    self.assertIn(f"`{row['model']}`", section)

    def test_every_capability_note_appears_verbatim(self):
        """The strongest coupling in the repo, and the point of the matrix.

        A note that changes in the config and not here means the reference is
        lying about the harness.
        """
        for harness in self.harnesses:
            section = self._section(harness)
            for row in self.config["capabilities"]:
                with self.subTest(harness=harness, capability=row["key"]):
                    self.assertIn(f"| {row['label']} |", section)
                    self.assertIn(row["values"][harness]["note"], section)

    def test_effortless_harnesses_explain_themselves(self):
        for harness in self.harnesses:
            rows = self.config["harnesses"][harness]
            if rows["effortSupport"]:
                continue
            with self.subTest(harness=harness):
                self.assertIn(rows["effortAbsentNote"], self._section(harness))
                self.assertIn("not selectable", self._section(harness))

    def test_every_native_substitution_is_disclosed(self):
        for harness in self.harnesses:
            section = self._section(harness)
            natives = self.config["harnesses"][harness].get("natives", {})
            for kind in ("roles", "skills"):
                for name, entry in natives.get(kind, {}).items():
                    with self.subTest(harness=harness, name=name):
                        self.assertIn(name, section)
                        self.assertIn(entry["native"], section)
                        self.assertIn(entry["reason"], section)

    def test_substituted_roles_are_marked_as_not_registered(self):
        for harness in self.harnesses:
            section = self._section(harness)
            natives = self.config["harnesses"][harness].get("natives", {}).get("roles", {})
            for name, entry in natives.items():
                if entry["verdict"] != "drop":
                    continue
                row = next(l for l in section.splitlines() if l.startswith(f"| `{name}` (role)"))
                with self.subTest(harness=harness, role=name):
                    self.assertIn("| no |", row)

    def test_claude_only_skills_are_named_in_every_section(self):
        exclusive = self.config["skills"]["claudeOnly"]
        for harness in self.harnesses:
            section = self._section(harness)
            for name in exclusive:
                with self.subTest(harness=harness, skill=name):
                    self.assertIn(f"`leo:{name}`", section)

    def test_every_leo_token_resolves_to_a_real_skill(self):
        known = _skill_dirs()
        for token in sorted(set(re.findall(r"leo:([a-z][a-z-]*)", self.text))):
            with self.subTest(token=token):
                self.assertIn(token, known)

    def test_claude_only_tokens_do_not_leak_into_other_sections(self):
        for harness in self.harnesses:
            if harness == "claude":
                continue
            section = self._section(harness)
            for leaked in ("CLAUDE_PLUGIN_ROOT", "[1m]"):
                with self.subTest(harness=harness, token=leaked):
                    self.assertNotIn(leaked, section)

    def _section(self, harness):
        """Slice on harness titles only.

        A harness section owns level-3 sub-headings (native substitutions, skill
        availability), so splitting on any `## ` truncated every section before
        the part most worth checking.
        """
        titles = [self.config["harnesses"][h]["title"] for h in self.harnesses]
        start = self.text.index(f"\n## {harness_title(self.config, harness)}")
        ends = [
            self.text.index(f"\n## {t}")
            for t in titles
            if f"\n## {t}" in self.text and self.text.index(f"\n## {t}") > start
        ]
        return self.text[start : min(ends)] if ends else self.text[start:]


if __name__ == "__main__":
    unittest.main()
