#!/usr/bin/env python3
"""Render harness adapters from config/models.json and canonical role prompts."""

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config" / "models.json"
ROLE_ROOT = ROOT / "roles"
CLAUDE_MANIFEST = ROOT / ".claude-plugin" / "plugin.json"
GENERATED = "<!-- Generated by scripts/render_adapters.py; do not edit. -->\n"
READ_ONLY = {"expert", "explore", "investigator", "planner", "reviewer"}


def _split_role(text):
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError("role prompt is missing YAML frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError("role prompt has unterminated YAML frontmatter") from exc
    return lines[1:end], "\n".join(lines[end + 1 :]).strip() + "\n"


def _without(frontmatter, keys):
    return [line for line in frontmatter if not any(line.startswith(key + ":") for key in keys)]


def _agent_docs(role, tier, config):
    source = (ROLE_ROOT / f"{role}.md").read_text(encoding="utf-8")
    frontmatter, body = _split_role(source)

    claude_frontmatter = _without(frontmatter, {"model", "effort"})
    claude_frontmatter.append(f"model: ${{user_config.{tier}_model}}")
    effort = config["harnesses"]["claude"][tier].get("effort")
    if effort:
        claude_frontmatter.append(f"effort: {effort}")
    claude = (
        "---\n"
        + "\n".join(claude_frontmatter)
        + "\n---\n\n"
        + GENERATED
        + "\n"
        + body
    )

    cursor_frontmatter = _without(frontmatter, {"model", "effort", "tools"})
    cursor_frontmatter.append("model: inherit")
    if role in READ_ONLY:
        cursor_frontmatter.append("readonly: true")
    cursor = (
        "---\n"
        + "\n".join(cursor_frontmatter)
        + "\n---\n\n"
        + GENERATED
        + "\n"
        + body
    )
    return claude, cursor


def _table(rows):
    lines = ["| Tier | Model | Effort |", "|---|---|---|"]
    for tier in ("fable", "opus", "sonnet", "haiku"):
        item = rows[tier]
        lines.append(f"| {tier.title()} | `{item['model']}` | {item.get('effort', 'native default')} |")
    return "\n".join(lines)


def _collapse_note(rows):
    """Name tiers that share one model on this harness.

    The policy treats the four tiers as distinct rungs, and its "no Fable
    tier here, cap escalation at Opus" branch only fires if the harness says
    so. A mapping that silently points two rungs at one model leaves that
    branch unreachable while the expert rung is materially fake.
    """
    by_model = {}
    for tier in ("fable", "opus", "sonnet", "haiku"):
        by_model.setdefault(rows[tier]["model"], []).append(tier)
    collapsed = [tiers for tiers in by_model.values() if len(tiers) > 1]
    if not collapsed:
        return ""
    groups = ", ".join(
        "≡".join(t.title() for t in tiers) + f" (`{rows[tiers[0]]['model']}`)"
        for tiers in collapsed
    )
    note = f"\nTier collapse here: {groups} — routing between collapsed rungs buys role, not power. "
    if any("fable" in tiers and "opus" in tiers for tiers in collapsed):
        note += (
            "Fable is not a real rung: `expert` cannot break a deadlock a "
            "collapsed Opus already lost, so cap escalation at Opus and report. "
        )
    return note.rstrip() + "\n"


def _mapping_docs(config):
    claude_rows = {
        tier: {
            "model": f"${{user_config.{tier}_model}}",
            **({"effort": item["effort"]} if "effort" in item else {}),
        }
        for tier, item in config["harnesses"]["claude"].items()
    }
    codex = config["harnesses"]["codex"]
    cursor = config["harnesses"]["cursor"]
    hermes = config["harnesses"]["hermes"]
    hermes_rows = {tier: hermes[tier] for tier in ("fable", "opus", "sonnet", "haiku")}
    return {
        "claude": GENERATED
        + "# Claude Code mapping\n\n"
        + _table(claude_rows)
        + "\n\nSpawn the named native agent; its generated frontmatter selects the configured model.\n"
        + _collapse_note(claude_rows),
        "codex": GENERATED
        + "# Codex mapping\n\n"
        + _table(codex)
        + "\n\nSpawn a generic subagent with the canonical `roles/<role>.md` prompt and pass both "
        "`model` and `reasoning_effort` explicitly. A model override in the user's prompt or "
        "native `AGENTS.md` wins over these defaults.\n"
        + _collapse_note(codex),
        "cursor": GENERATED
        + "# Cursor mapping\n\n"
        + _table(cursor)
        + "\n\nCursor plugin agents use `model: inherit`. Select the mapped model in Cursor before "
        "starting a homogeneous tier batch; the plugin does not claim to enforce arbitrary "
        "per-agent model names.\n"
        + _collapse_note(cursor),
        "hermes": GENERATED
        + "# Hermes mapping\n\n"
        + f"Provider: `{hermes['provider']}`\n\n"
        + _table(hermes_rows)
        + "\n\nHermes native `delegate_task` has one configured delegation model. Group work into "
        "homogeneous Kimi or GLM batches, switch the parent with `/model`, and set "
        "`delegation.provider: openrouter` plus the matching `delegation.model` before spawning.\n"
        + _collapse_note(hermes_rows),
    }


def render(config):
    outputs = {}
    for role, tier in sorted(config["roles"].items()):
        claude, cursor = _agent_docs(role, tier, config)
        # Claude Code agents MUST live at the conventional agents/ path: a
        # manifest "agents" array of file paths validates but silently loads
        # zero agents, and the conventional directory auto-loads.
        outputs[ROOT / "agents" / f"{role}.md"] = claude
        outputs[ROOT / "adapters" / "cursor" / "agents" / f"{role}.md"] = cursor
    for harness, content in _mapping_docs(config).items():
        outputs[ROOT / "skills" / "using-leo" / "references" / f"{harness}-mapping.md"] = content

    manifest = json.loads(CLAUDE_MANIFEST.read_text(encoding="utf-8"))
    for tier, item in config["harnesses"]["claude"].items():
        manifest["userConfig"][f"{tier}_model"]["default"] = item["model"]
    outputs[CLAUDE_MANIFEST] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    return outputs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated adapters drift")
    args = parser.parse_args()
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    outputs = render(config)
    drift = []
    for path, expected in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == expected:
            continue
        if args.check:
            drift.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if drift:
        print("generated adapter drift: " + ", ".join(drift), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
