#!/usr/bin/env python3
"""Render harness adapters from config/models.json and canonical role prompts."""

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config" / "models.json"
ROLE_ROOT = ROOT / "roles"
CLAUDE_MANIFEST = ROOT / ".claude-plugin" / "plugin.json"
GENERATED = "<!-- Generated by scripts/render_adapters.py; do not edit. -->\n"
READ_ONLY = {"expert", "explore", "investigator", "planner", "reviewer"}


def _split_role(text):
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError("role prompt is missing YAML frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError("role prompt has unterminated YAML frontmatter") from exc
    return lines[1:end], "\n".join(lines[end + 1 :]).strip() + "\n"


def _without(frontmatter, keys):
    return [line for line in frontmatter if not any(line.startswith(key + ":") for key in keys)]


def _agent_docs(role, tier, config):
    source = (ROLE_ROOT / f"{role}.md").read_text(encoding="utf-8")
    frontmatter, body = _split_role(source)

    claude_frontmatter = _without(frontmatter, {"model", "effort"})
    # Concrete model, never a plugin-config placeholder: Claude Code does not
    # interpolate plugin options into agent frontmatter, so a placeholder here
    # reaches the model selector verbatim and every spawn dies with "issue
    # with the selected model". config/models.json stays the one source.
    #
    # And a *bare* alias, never an alias with a context suffix: the agent
    # frontmatter `model` field documents exactly three accepted shapes — a
    # bare alias, a full model id, or `inherit`. `opus[1m]` is valid for
    # /model and for skill frontmatter, but it is not one of those three, so
    # it is the same undocumented-assumption bet that the placeholder was.
    # Skill frontmatter (skills-claude/*) keeps [1m]; agents do not.
    claude_frontmatter.append(f"model: {config['harnesses']['claude'][tier]['model']}")
    effort = config["harnesses"]["claude"][tier].get("effort")
    if effort:
        claude_frontmatter.append(f"effort: {effort}")
    claude = (
        "---\n"
        + "\n".join(claude_frontmatter)
        + "\n---\n\n"
        + GENERATED
        + "\n"
        + body
    )

    cursor_frontmatter = _without(frontmatter, {"model", "effort", "tools"})
    cursor_frontmatter.append("model: inherit")
    if role in READ_ONLY:
        cursor_frontmatter.append("readonly: true")
    cursor = (
        "---\n"
        + "\n".join(cursor_frontmatter)
        + "\n---\n\n"
        + GENERATED
        + "\n"
        + body
    )
    return claude, cursor


def _table(rows):
    lines = ["| Tier | Model | Effort |", "|---|---|---|"]
    for tier in ("fable", "opus", "sonnet", "haiku"):
        item = rows[tier]
        lines.append(f"| {tier.title()} | `{item['model']}` | {item.get('effort', 'native default')} |")
    return "\n".join(lines)


def _collapse_note(rows):
    """Name tiers that share one model on this harness.

    The policy treats the four tiers as distinct rungs, and its "no Fable
    tier here, cap escalation at Opus" branch only fires if the harness says
    so. A mapping that silently points two rungs at one model leaves that
    branch unreachable while the expert rung is materially fake.
    """
    by_model = {}
    for tier in ("fable", "opus", "sonnet", "haiku"):
        by_model.setdefault(rows[tier]["model"], []).append(tier)
    collapsed = [tiers for tiers in by_model.values() if len(tiers) > 1]
    if not collapsed:
        return ""
    groups = ", ".join(
        "≡".join(t.title() for t in tiers) + f" (`{rows[tiers[0]]['model']}`)"
        for tiers in collapsed
    )
    note = f"\nTier collapse here: {groups} — routing between collapsed rungs buys role, not power. "
    if any("fable" in tiers and "opus" in tiers for tiers in collapsed):
        note += (
            "Fable is not a real rung: `expert` cannot break a deadlock a "
            "collapsed Opus already lost, so cap escalation at Opus and report. "
        )
    return note.rstrip() + "\n"


def _skill_notes(config, harness):
    """Name the leo:* skills this harness does not get, and why.

    Silence here is worse than the exclusion: a policy Skill index that lists
    skills the harness never registered reads as "available" until someone
    invokes one. Reason strings describe placeholders in prose on purpose —
    tests/test_harness_mappings.py fails the build if the literal Claude
    token appears in a non-Claude mapping.
    """
    skills = config.get("skills", {})
    missing = set(skills.get("exclude", {}).get(harness, ()))
    if harness != "claude":
        missing |= set(skills.get("claudeOnly", ()))
    if not missing:
        return ""
    reasons = skills.get("reasons", {})
    lines = ["", "## Leo skills not available here", ""]
    for name in sorted(missing):
        lines.append(f"- `leo:{name}` — {reasons.get(name, 'not portable to this harness')}.")
    lines.append("")
    lines.append(
        "Every other skill in the policy's Skill index is registered here and "
        "behaves the same. Reviewing a pull request on this harness means "
        "running the canonical reviewer role prompt against the diff by hand."
    )
    return "\n".join(lines) + "\n"


def _mapping_docs(config):
    claude_rows = config["harnesses"]["claude"]
    codex = config["harnesses"]["codex"]
    cursor = config["harnesses"]["cursor"]
    hermes = config["harnesses"]["hermes"]
    hermes_rows = {tier: hermes[tier] for tier in ("fable", "opus", "sonnet", "haiku")}
    return {
        "claude": GENERATED
        + "# Claude Code mapping\n\n"
        + _table(claude_rows)
        + "\n\nSpawn the named native agent; its generated frontmatter selects the configured model.\n"
        + _collapse_note(claude_rows)
        + _skill_notes(config, "claude"),
        "codex": GENERATED
        + "# Codex mapping\n\n"
        + _table(codex)
        + "\n\nSpawn a generic subagent with the canonical `roles/<role>.md` prompt and pass both "
        "`model` and `reasoning_effort` explicitly. A model override in the user's prompt or "
        "native `AGENTS.md` wins over these defaults.\n"
        "\nRead-only is prompt-enforced here, not harness-enforced: the judge roles "
        "(planner, investigator, reviewer, explore) are pasted prompts, so nothing stops a "
        "subagent that ignores them from editing. Treat their read-only contract as a "
        "convention, and never route work here that depends on it being a guarantee.\n"
        + _collapse_note(codex)
        + _skill_notes(config, "codex"),
        "cursor": GENERATED
        + "# Cursor mapping\n\n"
        + _table(cursor)
        + "\n\nCursor plugin agents use `model: inherit`. Select the mapped model in Cursor before "
        "starting a homogeneous tier batch; the plugin does not claim to enforce arbitrary "
        "per-agent model names.\n"
        + _collapse_note(cursor)
        + _skill_notes(config, "cursor"),
        "hermes": GENERATED
        + "# Hermes mapping\n\n"
        + f"Provider: `{hermes['provider']}`\n\n"
        + _table(hermes_rows)
        + "\n\nHermes native `delegate_task` has one configured delegation model. Group work into "
        "homogeneous Kimi or GLM batches, switch the parent with `/model`, and set "
        "`delegation.provider: openrouter` plus the matching `delegation.model` before spawning.\n"
        "\nThis policy is NOT injected automatically here. Hermes accepts a `pre_llm_call` "
        "hook but its runtime never invokes one, so the plugin registers `leo:using-leo` as "
        "an ordinary skill instead — read it at the start of a session to load the policy. "
        "Read-only is prompt-enforced only: the judge roles are pasted prompts, so their "
        "read-only contract is a convention here, not a guarantee.\n"
        + _collapse_note(hermes_rows)
        + _skill_notes(config, "hermes"),
    }


def render(config):
    outputs = {}
    for role, tier in sorted(config["roles"].items()):
        claude, cursor = _agent_docs(role, tier, config)
        # Claude Code agents MUST live at the conventional agents/ path: a
        # manifest "agents" array of file paths validates but silently loads
        # zero agents, and the conventional directory auto-loads.
        outputs[ROOT / "agents" / f"{role}.md"] = claude
        outputs[ROOT / "adapters" / "cursor" / "agents" / f"{role}.md"] = cursor
    for harness, content in _mapping_docs(config).items():
        outputs[ROOT / "skills" / "using-leo" / "references" / f"{harness}-mapping.md"] = content

    # The manifest is no longer rewritten here: per-install model overrides
    # were retired along with the placeholder they fed. Retiering means editing
    # config/models.json and re-running this script, the flow README documents.
    return outputs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated adapters drift")
    args = parser.parse_args()
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    outputs = render(config)
    drift = []
    for path, expected in outputs.items():
        if path.exists() and path.read_text(encoding="utf-8") == expected:
            continue
        if args.check:
            drift.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    # Stale generated files are drift too. Comparing only what render() would
    # produce is blind to a file that exists and *shouldn't* — a role dropped
    # from models.json, a harness renamed — so the orphan survives every
    # --check and ships. Sweep the generated trees and flag anything unclaimed.
    for pattern in (
        "agents/*.md",
        "adapters/cursor/agents/*.md",
        "skills/using-leo/references/*-mapping.md",
    ):
        for path in sorted(ROOT.glob(pattern)):
            if path in outputs:
                continue
            rel = path.relative_to(ROOT).as_posix()
            if args.check:
                drift.append(f"{rel} (stale: nothing in config/models.json generates it)")
            else:
                path.unlink()
                print(f"removed stale generated file: {rel}", file=sys.stderr)
    if drift:
        print("generated adapter drift: " + ", ".join(drift), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
